name: cvse
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - absl-py==2.2.1
      - astunparse==1.6.3
      - cachetools==5.5.2
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - contourpy==1.3.1
      - cycler==0.12.1
      - earthengine-api==1.5.12
      - flatbuffers==25.2.10
      - fonttools==4.56.0
      - future==1.0.0
      - gast==0.6.0
      - google-api-core==2.24.2
      - google-api-python-client==2.167.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-cloud-core==2.4.3
      - google-cloud-storage==3.1.0
      - google-crc32c==1.7.1
      - google-pasta==0.2.0
      - google-resumable-media==2.7.2
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - h5py==3.13.0
      - httplib2==0.22.0
      - httplib2shim==0.0.3
      - idna==3.10
      - joblib==1.4.2
      - keras==2.13.1
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.8
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mdurl==0.1.2
      - ml-dtypes==0.3.2
      - namex==0.0.8
      - numpy==1.26.4
      - oauthlib==3.2.2
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optree==0.14.1
      - pillow==11.1.0
      - proto-plus==1.26.1
      - protobuf==4.25.6
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - rich==14.0.0
      - rsa==4.9.1
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - uritemplate==4.1.1
      - urllib3==2.3.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
